OficialDjango/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('poll/', include("poll.urls"))
]

poll/urls.py
from django.urls import path
from . import views

app_name = "poll"
urlpatterns = [
    path("", views.IndexView.as_view(), name="index"),
    path("<int:question_id>/", views.detail, name="detail"),
    path("<int:question_id>/results/", views.results, name="results"),
    path("<int:question_id>/vote/", views.vote, name="vote"),
]

poll/models.py
from django.db import models

from django.utils import timezone
from django.contrib import admin
import datetime

# Create your models here.

class Question(models.Model):
    quest_text = models.CharField(max_length = 200)
    pub_date = models.DateTimeField("date published")
    
    @admin.display(
        boolean = True, 
        ordering = "pub_date",
        description = "Published recently?"
    )
    
    def was_published_recently(self):
        now = timezone.now()
        return now - datetime.timedelta(days=1) <= self.pub_date <= now
    def __str__(self) -> str:
        return self.quest_text
    
  
class Choice(models.Model):
    question = models.ForeignKey(Question, on_delete = models.CASCADE)
    choice_text = models.CharField(max_length = 200)
    votes= models.IntegerField(default = 0)
    
    def __str__(self) -> str:
        return self.choice_text
    

poll/views.py
from django.shortcuts import render
from django.http import HttpResponse, Http404, HttpResponseRedirect
from django.urls import reverse
from django.views import generic
from django.utils import timezone

from .models import Question, Choice


# Create your views here.
class IndexView(generic.ListView):
    template_name = "poll/index.html"
    context_object_name = "latest_quest_list"

    def get_queryset(self):
        
        return Question.objects.filter(pub_date__lte=timezone.now()).order_by("-pub_date")[:5]
def prueba(request):
    
    return HttpResponse("esto es la mama de la mama")

def detail(request, question_id):
    try:
        
        operadores = { 
        "question" : Question.objects.get(pk=question_id),
        "choices" : Choice.objects.filter(question= question_id)
    }
    except Question.DoesNotExist:
        
        raise Http404("Question does not exist")
        
    return render(request, "poll/details.html", operadores) 

def results(request, question_id):
    
    operadores = { 
        "question" : Question.objects.get(pk=question_id),
        "choices" : Choice.objects.filter(question= question_id)
    }
    
    return render(request, "poll/results.html", operadores)

def vote(request, question_id):
    question = Question.objects.get(pk=question_id)
    try:
        selected_choice = question.choice_set.get(pk=request.POST["choice"])
    
    except (KeyError, Choice.DoesNotExist):
    
        return render(request, "poll/detail.html", {"question":question, "error_message":"you didn't select a choice"})
    
    else:
        selected_choice.votes += 1
        selected_choice.save()
        
        return HttpResponseRedirect(reverse("poll:results", args=(str(question.id))))

poll/templates/poll/details.html
<form action="{% url "poll:vote" question.id %}" method="post">
    {% csrf_token %}
<fieldset>
    <legend><h1>{{question.quest_text}}</h1></legend>
    {% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}
{% for choice in choices %}
        <input type="radio" name="choice" id="choice {{forloop.counter}}" value="{{choice.id}}">
        <label for="choice{{forloop.counter}}">{{choice.choice_text}}</label>

{% endfor %}
</fieldset>
<input type="submit" value="Vote">
<a href="/poll/">Go back</a>
</form>

poll/templates/poll/index.html
{% load static %}
<link rel="stylesheet" href="{% static "poll/style.css" %}">

{% if latest_quest_list %}

    <ul>
        {% for question in latest_quest_list %}
            <li><a href="{% url "poll:detail" question.id %}">{{question.quest_text}}</a></li>
        {% endfor %}
    
    </ul>

   
{% else %}

    <p>No polls are available. </p>

{% endif %}

poll/templates/poll/results.html
<h1>{{question.quest_text}}</h1>

{% for choice in choices %}
    <li>{{choice.choice_text}} -- {{choice.votes}} vote{{choice.votes| pluralize }}</li>
{% endfor %}
<br>
<a href="{% url "poll:detail" question.id %}">Vote again?</a>